### PR TITLE
Fix tooltip message when port scan is disabled

### LINKED ISSUE #11: Misleading tooltip texts for ongoing & non-enabled portscans
The tooltips for ongoing port scans claim that the tested port is open (when in fact we don't know that yet, as the test is ongoing):

undecided

Port scans that are not enabled (e.g. in Safari) do show that the test is not supported, but also claims that the port is closed:

not enabled

### PR DESCRIPTION
**Pull request by oherrala**
Fixes #11

### CODE REVIEW

File: src/client/index.js [hunk 1]
```diff
@@ -241,9 +241,16 @@ tests.append(
...
+            let title = "";
+            if (scan.disabled) {
+                title = "No result for " + portText;
+            } else {
+                if (scan.closed) {
+                    title = "Port for " + portText + " seems to be closed (" + scan.error + ")";
+                } else {
+                    title = "Port for " + portText + " seems to be open";
+                }
+            }
```
Comment (jviide) [inline src/client/index.js]: These conditions could be flattened to:

```js
if (scan.disabled) {
    ...
} else if (!scan.done) {
    ...
} else if (scan.error) {
    ...
} else {
    ...
}
```

File: src/client/index.js [hunk 2]
```diff
@@ -241,9 +241,16 @@ tests.append(
...
             const portText = scan.transport + ":" + scan.port + " (" + scan.name + ")";
 
-            const title = scan.error
-              ? "Port for " + portText + " seems to be closed (" + scan.error + ")"
-              : "Port for " + portText + " seems to be open";
+            let title = "";
+            if (scan.disabled) {
+                title = "No result for " + portText;
+            } else {
+                if (scan.closed) {
```
Comment (jviide) [inline src/client/index.js]: Do scan objects have a `closed` attribute? You most likely want to use `scan.done` ("does the scan have a verdict?") and `scan.error` ("the test failed/errored").
